id: I51B9FE5F
initial_creation_type: ebook
source_metadata:
  id: PUN-TG-002
  title: རང་བཞིན་རྫོགས་པ་ཆེན་པོ་ཀློང་གསལ་སྙིང་ཐིག་དང་ཟབ་ལམ་གསང་འདུས་ཀྱི་སྔོན་འགྲོ་ལམ་སྟེགས་ཤིང་རྟའི་ལམ་སྲོལ་ལུང་གི་གཏེར་མཛོད་ལམ་རིམ་ཐེམ་
  author: མཛད་པ་པོ། ཚངས་དབྱངས་རྒྱ་མཚོ།
  authors: &id001
  - མཛད་པ་པོ། ཚངས་དབྱངས་རྒྱ་མཚོ།
  sku: PUN-TG-002
  cover: TSG-002.jpg
  volume: {}
  title_source: epub:dc:title:ambiguous-layer
ebook_metadata:
  title: རང་བཞིན་རྫོགས་པ་ཆེན་པོ་ཀློང་གསལ་སྙིང་ཐིག་དང་ཟབ་ལམ་གསང་འདུས་ཀྱི་སྔོན་འགྲོ་ལམ་སྟེགས་ཤིང་རྟའི་ལམ་སྲོལ་ལུང་གི་གཏེར་མཛོད་ལམ་རིམ་ཐེམ་
  authors: *id001
  sku: PUN-TG-002
  cover: TSG-002.jpg
layers:
- Author
- BookTitle
- Citation
- Commentary
- Sabche
- Tsawa
